version: '2'
services:
  docker_exporter:
    image: shalb/docker_exporter:0.0.1
    volumes:
      - ./docker_exporter/exporter:/opt/exporter
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always
    ports:
      - "127.0.0.1:8088:8088"

